name: ci-release-controllers

on:
  push:
    branches:
      - "main"
    paths:
      - "pkg/**"

env:
  PLATFORM: linux/amd64,linux/arm64/v8

jobs:
  kubearmor-controller-release:
    name: Build & Push KubeArmorController
    if: github.repository == 'kubearmor/kubearmor'
    defaults:
      run:
        working-directory: ./pkg/KubeArmorController
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "v1.20"

      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AUTHTOK }}

      - name: Build & Push KubeArmorController
        run: PLATFORM=$PLATFORM make docker-buildx TAG=latest
